"""A/B test: FLUX.1-dev 12B (arm A) vs FLUX.2-klein-9B-KV-FP8 (arm B).

Arm A — current production: RunPod/Vast FLUX.1-dev 12B, text-to-image, prompt-only.
Arm B — experimental: Klein-9B-KV-FP8, text-to-image for env/object scenes,
         img2img with fixed reference images for character scenes.

Runs 20 scenes (configurable via --count) from an existing video's image_prompts.json.
Each scene is generated by both arms. Results are written to:

  output/ab_test_klein/<video_id>/
    arm_a/<scene_id>.png
    arm_b/<scene_id>.png
    arm_b_mode.json          # t2i or img2img per scene
    metrics.json             # timing, cost estimate, failure counts
    report.md                # human-readable summary + recommendation

Usage:
  python scripts/ab_test_klein.py --video-id my-video --klein-host 1.2.3.4 --klein-port 8081
  python scripts/ab_test_klein.py --video-id my-video --dry-run

Flags:
  --count N           Number of scenes to test (default: KLEIN_AB_SCENE_COUNT from config)
  --dry-run           Print scene plan, skip generation
  --runpod-arm-a      Use RunPod for arm A instead of local fake backend
  --arm-a-host HOST   Use a live Vast arm-A backend at HOST:PORT
  --arm-a-port PORT
  --klein-host HOST   Klein worker host
  --klein-port PORT
  --reference-dir DIR Override reference image directory
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from loguru import logger

import config
from image_generation.character_bible import detect_characters_in_text
from image_generation.scene_classifier import classify_scene


# ---------------------------------------------------------------------------
# Cost model
# ---------------------------------------------------------------------------

# Estimates based on Vast.ai RTX 3090 @ $0.24/100 imgs (from memory/worklog)
# Klein-9B at 4 steps should be ~2× faster than 12B at 20 steps → half cost
_COST_PER_100_IMAGES_12B = 0.24   # USD, Vast, RTX 3090
_COST_PER_100_IMAGES_KLEIN = 0.12  # estimated: 2× faster + lighter model
_SECONDS_PER_IMAGE_12B = 6.5       # observed average
_SECONDS_PER_IMAGE_KLEIN_T2I = 2.0
_SECONDS_PER_IMAGE_KLEIN_IMG2IMG = 3.5


def _estimate_cost(n: int, seconds_per_image: float, cost_per_100: float) -> dict:
    total_seconds = n * seconds_per_image
    cost = (n / 100) * cost_per_100
    return {
        "image_count": n,
        "estimated_seconds": round(total_seconds, 1),
        "estimated_cost_usd": round(cost, 4),
    }


# ---------------------------------------------------------------------------
# Scene planning
# ---------------------------------------------------------------------------

def _plan_scenes(video_id: str, count: int) -> list[dict]:
    prompts_path = Path(config.OUTPUT_DIR) / video_id / "image_prompts.json"
    if not prompts_path.exists():
        raise FileNotFoundError(f"image_prompts.json not found: {prompts_path}")
    prompts = json.loads(prompts_path.read_text(encoding="utf-8"))
    prompts = prompts[:count]

    plan = []
    for item in prompts:
        scene_text = item.get("scene_text") or item.get("prompt", "")
        chars = detect_characters_in_text(scene_text)
        classification = classify_scene(scene_text, characters=chars)
        has_character = bool(chars) or classification.scene_type.startswith("character")
        plan.append({
            "index": item["index"],
            "scene_id": f"{int(item['index']):03d}",
            "prompt": item.get("prompt", ""),
            "clip_prompt": item.get("clip_prompt", item.get("prompt", "")),
            "negative_prompt": item.get("negative_prompt", ""),
            "scene_type": classification.scene_type,
            "has_character": has_character,
            "arm_b_mode": "img2img" if has_character else "text_to_image",
            "confidence": round(classification.confidence, 2),
        })
    return plan


# ---------------------------------------------------------------------------
# Generation helpers (arm A and arm B)
# ---------------------------------------------------------------------------

def _build_arm_a_backend(args) -> object:
    if args.arm_a_host:
        from image_generation.vast_backend import VastInstanceBackend
        token = config.WORKER_API_TOKEN or ""
        return VastInstanceBackend(
            host=args.arm_a_host,
            port=args.arm_a_port,
            worker_token=token,
        )
    if args.runpod_arm_a:
        from image_generation.runpod_client import RunPodClient
        from image_generation.runpod_serverless_backend import RunPodServerlessBackend
        if not config.RUNPOD_API_KEY:
            raise RuntimeError("RUNPOD_API_KEY not set for arm A RunPod")
        client = RunPodClient(
            api_key=config.RUNPOD_API_KEY,
            endpoint_id=config.RUNPOD_ENDPOINT_ID,
            timeout=config.RUNPOD_REQUEST_TIMEOUT,
            poll_interval=config.RUNPOD_POLL_INTERVAL,
            max_retries=config.RUNPOD_MAX_RETRIES,
        )
        return RunPodServerlessBackend(client=client)
    # Dry-run / offline: use a no-op backend
    return _NoOpBackend(arm="A")


def _build_arm_b_backend(args) -> object:
    if args.klein_host:
        from image_generation.klein_backend import KleinBackend
        token = config.WORKER_API_TOKEN or ""
        ref_dir = args.reference_dir or config.KLEIN_REFERENCE_DIR
        return KleinBackend(
            host=args.klein_host,
            port=args.klein_port,
            worker_token=token,
            master_seed_dir=ref_dir if Path(ref_dir).exists() else None,
            steps_t2i=config.KLEIN_STEPS_T2I,
            steps_img2img=config.KLEIN_STEPS_IMG2IMG,
            strength_character=config.KLEIN_IMG2IMG_STRENGTH_CHARACTER,
            strength_continuity=config.KLEIN_IMG2IMG_STRENGTH_CONTINUITY,
        )
    return _NoOpBackend(arm="B")


class _NoOpBackend:
    """Stand-in backend for dry-run or offline testing."""
    def __init__(self, arm: str):
        self._arm = arm

    def health_check(self) -> bool:
        return True

    def generate(self, request):
        from image_generation.schemas import SceneResult
        return SceneResult(
            video_id=request.video_id,
            scene_id=request.scene_id,
            model=f"noop/{self._arm}",
            mode="noop",
            duration_seconds=0.0,
            candidates=[],
            errors=[f"dry_run: arm {self._arm} not connected"],
        )


# ---------------------------------------------------------------------------
# Main runner
# ---------------------------------------------------------------------------

def _run_arm(backend, scenes: list[dict], arm_name: str, out_dir: Path) -> dict:
    from image_generation.schemas import SceneRequest

    out_dir.mkdir(parents=True, exist_ok=True)
    results = []
    for scene in scenes:
        req = SceneRequest(
            video_id="ab_test",
            scene_id=scene["scene_id"],
            prompt=scene["prompt"],
            clip_prompt=scene["clip_prompt"],
            negative_prompt=scene["negative_prompt"],
            width=config.IMAGE_WIDTH,
            height=config.IMAGE_HEIGHT,
            steps=config.IMAGE_STEPS,
            guidance_scale=config.IMAGE_GUIDANCE_SCALE,
            candidate_seeds=config.KLEIN_AB_CANDIDATE_SEEDS,
            output_format="PNG",
            quality=config.IMAGE_QUALITY,
        )
        t0 = time.time()
        result = backend.generate(req)
        elapsed = round(time.time() - t0, 2)

        ok = len(result.candidates) > 0
        if ok:
            # Save best candidate as arm's output
            best = result.candidates[0]
            dest = out_dir / f"{scene['scene_id']}.png"
            if best.local_path and Path(best.local_path).exists():
                import shutil
                shutil.copy2(best.local_path, dest)
            elif best.base64_data:
                import base64 as b64
                dest.write_bytes(b64.b64decode(best.base64_data))

        results.append({
            "scene_id": scene["scene_id"],
            "scene_type": scene["scene_type"],
            "arm_b_mode": scene.get("arm_b_mode", "text_to_image"),
            "ok": ok,
            "elapsed_seconds": elapsed,
            "errors": result.errors,
        })
        status = "ok" if ok else "FAIL"
        logger.info("Arm {}: scene={} {} in {:.1f}s", arm_name, scene["scene_id"], status, elapsed)

    return {
        "arm": arm_name,
        "total": len(results),
        "ok": sum(1 for r in results if r["ok"]),
        "fail": sum(1 for r in results if not r["ok"]),
        "total_seconds": round(sum(r["elapsed_seconds"] for r in results), 2),
        "scenes": results,
    }


def _write_report(video_id: str, out_base: Path, plan: list[dict], arm_a: dict, arm_b: dict) -> None:
    n = arm_a["total"]
    n_char = sum(1 for s in plan if s["has_character"])
    n_env = n - n_char

    cost_a = _estimate_cost(n, _SECONDS_PER_IMAGE_12B, _COST_PER_100_IMAGES_12B)
    avg_klein = (
        (_SECONDS_PER_IMAGE_KLEIN_IMG2IMG * n_char + _SECONDS_PER_IMAGE_KLEIN_T2I * n_env) / n
        if n > 0 else _SECONDS_PER_IMAGE_KLEIN_T2I
    )
    cost_b = _estimate_cost(n, avg_klein, _COST_PER_100_IMAGES_KLEIN)

    metrics = {
        "video_id": video_id,
        "scene_count": n,
        "character_scenes": n_char,
        "env_object_scenes": n_env,
        "arm_a": {
            **arm_a,
            "cost_estimate": cost_a,
        },
        "arm_b": {
            **arm_b,
            "cost_estimate": cost_b,
        },
    }
    (out_base / "metrics.json").write_text(
        json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # Arm B mode breakdown
    mode_log = {s["scene_id"]: s.get("arm_b_mode", "text_to_image") for s in plan}
    (out_base / "arm_b_mode.json").write_text(
        json.dumps(mode_log, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    # Human-readable report (provisional — to be filled after visual inspection)
    speed_ratio = (arm_b["total_seconds"] / arm_a["total_seconds"]) if arm_a["total_seconds"] > 0 else 0
    cost_savings_pct = round((1 - cost_b["estimated_cost_usd"] / max(cost_a["estimated_cost_usd"], 1e-9)) * 100, 1)

    lines = [
        f"# A/B Test Report — {video_id}",
        "",
        f"Tested {n} scenes ({n_char} character, {n_env} env/object/diagram).",
        "",
        "## Generation results",
        f"| Metric | Arm A (12B FLUX.1-dev) | Arm B (9B Klein) |",
        f"|--------|------------------------|------------------|",
        f"| OK     | {arm_a['ok']}/{n} | {arm_b['ok']}/{n} |",
        f"| Fail   | {arm_a['fail']} | {arm_b['fail']} |",
        f"| Total time | {arm_a['total_seconds']:.1f}s | {arm_b['total_seconds']:.1f}s |",
        f"| Est. cost/batch | ${cost_a['estimated_cost_usd']:.4f} | ${cost_b['estimated_cost_usd']:.4f} |",
        f"| Speed ratio | 1.00× | {speed_ratio:.2f}× |",
        f"| Est. cost savings | — | {cost_savings_pct}% |",
        "",
        "## Arm B scene breakdown",
        f"- img2img (character): {n_char} scenes @ strength={config.KLEIN_IMG2IMG_STRENGTH_CHARACTER}",
        f"- text-to-image (env/obj): {n_env} scenes",
        "",
        "## Visual quality (fill in after inspection)",
        "",
        "| Dimension | Score A | Score B | Winner |",
        "|-----------|---------|---------|--------|",
        "| Character consistency | — | — | — |",
        "| Prompt fidelity | — | — | — |",
        "| Artistic quality | — | — | — |",
        "",
        "## Recommendation",
        "",
        "TODO: complete after visual inspection of arm_a/ vs arm_b/ images.",
        "",
        "Criteria for switching to Klein-9B:",
        "- Character consistency >= arm A (visual check)",
        "- Prompt fidelity OK for env/obj scenes",
        "- Failure rate <= arm A",
        "- Cost saving >= 30% (currently estimated: " + f"{cost_savings_pct}%)",
        "",
        "Criteria for keeping 12B:",
        "- Klein character scenes have visible drift or clothing violations",
        "- Fidelity worse on env/diagram scenes",
        "- Failure rate higher",
    ]
    (out_base / "report.md").write_text("\n".join(lines), encoding="utf-8")
    logger.info("Report written to {}", out_base / "report.md")


def main() -> None:
    parser = argparse.ArgumentParser(description="A/B test: 12B (arm A) vs Klein-9B (arm B)")
    parser.add_argument("--video-id", required=True, metavar="VIDEO_ID")
    parser.add_argument("--count", type=int, default=config.KLEIN_AB_SCENE_COUNT)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--runpod-arm-a", action="store_true", help="Use RunPod for arm A")
    parser.add_argument("--arm-a-host", default="", metavar="HOST")
    parser.add_argument("--arm-a-port", type=int, default=8080)
    parser.add_argument("--klein-host", default="", metavar="HOST")
    parser.add_argument("--klein-port", type=int, default=config.KLEIN_WORKER_PORT)
    parser.add_argument("--reference-dir", default="", metavar="DIR")
    args = parser.parse_args()

    plan = _plan_scenes(args.video_id, args.count)
    out_base = Path(config.KLEIN_AB_OUTPUT_DIR) / args.video_id
    out_base.mkdir(parents=True, exist_ok=True)

    # Print plan
    logger.info("A/B plan: {} scenes ({} character, {} env/obj)",
                len(plan),
                sum(1 for s in plan if s["has_character"]),
                sum(1 for s in plan if not s["has_character"]))
    for s in plan:
        logger.info("  {:3d} {:30s} arm_b={} char={}",
                    s["index"], s["scene_type"][:30], s["arm_b_mode"], s["has_character"])

    if args.dry_run:
        (out_base / "plan.json").write_text(
            json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        logger.info("Dry run: plan written to {}", out_base / "plan.json")
        return

    arm_a_backend = _build_arm_a_backend(args)
    arm_b_backend = _build_arm_b_backend(args)

    logger.info("Running arm A (12B FLUX.1-dev)...")
    arm_a_results = _run_arm(arm_a_backend, plan, "A", out_base / "arm_a")

    logger.info("Running arm B (Klein-9B)...")
    arm_b_results = _run_arm(arm_b_backend, plan, "B", out_base / "arm_b")

    _write_report(args.video_id, out_base, plan, arm_a_results, arm_b_results)
    logger.info("A/B test complete. Results: {}", out_base)


if __name__ == "__main__":
    main()
